version: '3'

services:
  nginx:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - /nginx/config/:/etc/nginx/
      # - /nginx/certs:/etc/ssl/private
    deploy:
      placement:
        constraints:
          - node.role == manager
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
  catnip:
    image: dsessler7/catnip:latest
    container_name: catnip
    restart: unless-stopped
    expose:
      - 5000
configs:
  nginx_config:
    file: /nginx/config/nginx.conf